# marketing-timeline values

fullnameOverride: marketing-timeline

replicaCount: 1

image:
  repository: 679574531779.dkr.ecr.ap-northeast-2.amazonaws.com/marketing-timeline
  tag: "ede030ce2f2dc8a597a07af459c9534df4ba66c3"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

spring:
  profiles:
    active: "aws"

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 512Mi
