# marketing-like values

fullnameOverride: marketing-like

replicaCount: 1

image:
  repository: 679574531779.dkr.ecr.ap-northeast-2.amazonaws.com/marketing-like
  tag: "6f5ebf83311b492ff73fbbbfbdae4cf1b093215f"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

spring:
  profiles:
    active: "aws"

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 512Mi
