{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-boot-msa.fullname" . }}
  labels:
    {{- include "spring-boot-msa.labels" . | nindent 4 }}
{{- with .Values.configMap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}